name: Build

on: [workflow_call]

env:
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: cargohub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}

      - uses: actions/checkout@v4

      - name: Debug Environment Variables
        run: |
          echo "OWNER=${OWNER}"
          echo "IMAGE_NAME=${IMAGE_NAME}"

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/$OWNER_LC/$IMAGE_NAME:build-${{ github.run_id }}
