name: CI/CD - Testing

on:
  workflow_call:
    inputs:
      DEPLOY_WEBHOOK_URL:
        type: string
        required: true

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Run code formatting check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Restore unit test dependencies
        run: |
          cd ./unit_tests
          dotnet restore

      - name: Run .NET tests with coverage
        id: run_dotnet_tests
        run: |
          cd ./unit_tests
          dotnet test --configuration Release --no-restore --collect:"XPlat Code Coverage" --results-directory cobertura

      - name: Run Python tests with coverage
        id: run_python_tests
        run: |
          pytest --cov=integration_tests --cov-report=xml --cov-report=term-missing || exit 1
          coverage xml -o coverage.xml

      - name: Notify Discord about Test Completion
        if: always()
        run: |
          error_message=""
          if [ "${{ steps.run_dotnet_tests.outcome }}" == "failure" ]; then
            error_message+="❌ **.NET Tests failed**:\n$(cat unit_tests/cobertura/*/coverage.cobertura.xml | tail -n 20)\n"
          fi
          if [ "${{ steps.run_python_tests.outcome }}" == "failure" ]; then
            error_message+="❌ **Python Tests failed**:\n$(tail -n 20 coverage.xml)\n"
          fi
          if [ -z "$error_message" ]; then
            error_message="✅ **All tests passed successfully** for the branch."
          fi
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "'"$error_message"'"}' \
          "${{ inputs.DEPLOY_WEBHOOK_URL }}"
