name: CI/CD - test

on:
  push:
    branches:
      staging
  pull_request:
    branches:
      - main
      - staging

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run code formatting check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Run tests
        run: dotnet test --configuration Release --no-restore
        continue-on-error: true

      - name: Notify Discord about Test Completion
        env:
          WEBHOOK_URL: ${{secrets.DEPLOY_WEBHOOK_URL}}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "✅ **Testing stage completed successfully** for staging branch, despite potential errors."}' \
          "$WEBHOOK_URL"