name: CI/CD - deploy 

on:
    push:
        branches:
            - main
            - 93
    pull_request:
        branches:
            - main
            - 93

env:
  IMAGE_NAME: cargohub
  OWNER: "${{ github.repository_owner }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}

      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/$OWNER_LC/$IMAGE_NAME:build-${{ github.run_id }}


  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}

      - name: Build and Push the Docker image (push to main)
        if: github.event_name == 'push'
        run: |
          docker build . --tag ghcr.io/$OWNER_LC/$IMAGE_NAME:latest
          docker push ghcr.io/$OWNER_LC/$IMAGE_NAME:latest

      - name: Send HTTP request with curl (only on push)
        if: github.event_name == 'push'
        env:
            WEBHOOK_URL: ${{secrets.DEPLOY_WEBHOOK_URL}}
        run: |
          curl -X POST -k "$WEBHOOK_URL"