name: CI/CD - deploy 

on:
    workflow_call:
        inputs:
          DEPLOY_WEBHOOK_URL:
            type: string
            required: true

env:
  IMAGE_NAME: cargohub
  OWNER: "${{ github.repository_owner }}"

jobs:
  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}

      - name: Build and Push the Docker image (push to main)
        if: github.event_name == 'push'
        run: |
          docker build . --tag ghcr.io/$OWNER_LC/$IMAGE_NAME:latest
          docker push ghcr.io/$OWNER_LC/$IMAGE_NAME:latest

      - name: Send HTTP request with curl (only on push)
        if: github.event_name == 'push'
        run: |
          curl -X POST -k ${{inputs.DEPLOY_WEBHOOK_URL}}