name: CI/CD - Main Branch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: cargohub
  OWNER: "${{ github.repository_owner }}"

jobs:
  build:
    uses: ./.github/workflows/ci-cd-build.yml

  # Test Stage
  test:
    uses: ./.github/workflows/ci-cd-testing.yml

  # Deploy Stage
  deploy:
    uses: ./.github/workflows/ci-cd-deploy.yml
