name: CI/CD - test

on:
  workflow_call:
    inputs:
      DEPLOY_WEBHOOK_URL:
        type: string
        required: true

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Run code formatting check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Run .NET tests
        run: dotnet test --configuration Release --no-restore
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r integration_tests/requirements.txt

      - name: Run application
        run: dotnet run --no-build --configuration Release --urls=${{ secrets.LOCALHOST }} & sleep 5

      - name: Run Python integration tests with coverage
        run: pytest --cov=integration_tests --cov-fail-under=90 --junitxml=integration_tests/results.xml

      - name: Create test summary
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: integration_tests/results.xml

      - name: Notify Discord about Test Completion
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "✅ **Testing stage completed successfully** for staging branch, despite potential errors."}' \
          ${{inputs.DEPLOY_WEBHOOK_URL}}