name: CI/CD - test

on:
  workflow_call:
    inputs:
      DEPLOY_WEBHOOK_URL:
        type: string
        required: true

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Install .NET dependencies
        run: dotnet restore

      - name: Run code formatting check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Restore unit test dependencies
        run: |
          cd ./unit_tests
          dotnet restore

      - name: Run .NET tests
        run: |
          cd ./unit_tests
          dotnet test --configuration Release --no-restore
        continue-on-error: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r integration_tests/requirements.txt

      - name: Run application
        run: dotnet run --no-build --configuration Release --urls=${{ secrets.LOCALHOST }} & sleep 5

      - name: Run Python integration tests with coverage
        id: run_python_tests
        run: |
          pytest --cov=integration_tests --cov-report=xml --cov-report=term-missing
          coverage xml -o coverage.xml
          coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
          coverage report --fail-under=90

      - name: Notify Discord about Test Completion
        if: always()
        run: |
          error_message=""
          if [ "${{ steps.run_dotnet_tests.outcome }}" == "failure" ]; then
            dotnet_errors=$(cat unit_tests/cobertura/*/coverage.cobertura.xml | tail -n 20)
            error_message+="❌ **.NET Tests failed**:\n$dotnet_errors\n"
          fi
          if [ "${{ steps.run_python_tests.outcome }}" == "failure" ]; then
            python_errors=$(tail -n 20 coverage.xml)
            error_message+="❌ **Python Tests failed**:\n$python_errors\n"
          fi
          if [ -z "$error_message" ]; then
            error_message="✅ **All tests passed successfully** for the branch."
          fi
          coverage_summary=$(cat $GITHUB_STEP_SUMMARY)
          error_message+="\n**Coverage Summary:**\n$coverage_summary"
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "'"$error_message"'"}' \
          ${{ inputs.DEPLOY_WEBHOOK_URL }}
