name: CI - Staging Branch

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Notify Discord about Build Completion
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "🚀 **Build stage completed successfully** for staging branch. Proceeding to testing stage."}' \
          https://discord.com/api/webhooks/1308371538604593252/uvcFk3Jkv4qu8RafmSzttiMdFyqX1VRY_i7M1rN85Ne9TdQhBMIQVRYGllOBFJRPrE60

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run code formatting check
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Run tests
        run: dotnet test --configuration Release --no-restore
        continue-on-error: true

      - name: Notify Discord about Test Completion
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "✅ **Testing stage completed successfully** for staging branch, despite potential errors."}' \
          https://discord.com/api/webhooks/1308371538604593252/uvcFk3Jkv4qu8RafmSzttiMdFyqX1VRY_i7M1rN85Ne9TdQhBMIQVRYGllOBFJRPrE60
