name: CI - Staging Branch

on:
  push:
    branches:
      - 93
  pull_request:
    branches:
      - staging    
  workflow_dispatch:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build:
    uses: ./.github/workflows/ci-cd-build.yml
    with:
      DEPLOY_WEBHOOK_URL: ${{ inputs.DEPLOY_WEBHOOK_URL }}

  test:
    needs: build
    uses: ./.github/workflows/ci-cd-testing.yml
    with:
      DEPLOY_WEBHOOK_URL: ${{ inputs.DEPLOY_WEBHOOK_URL }}
