name: CI - Staging Branch

on:
  push:
    branches:
      - 154-as-a-developer-i-want-to-add-integration-tests-for-compatibility-with-v2-endpoints-in-the-following-files-cross-docking
  workflow_dispatch:

env:
  DOTNET_INSTALL_DIR: "./.dotnet"

jobs:
  build:
    uses: ./.github/workflows/ci-cd-build.yml
    with:
      DISCORD_WEBHOOK_URL: ${{ vars.DISCORD_WEBHOOK_URL }}

  test:
    needs: build
    uses: ./.github/workflows/ci-cd-testing.yml
    with:
      DEPLOY_WEBHOOK_URL: ${{ vars.DISCORD_WEBHOOK_URL }}
  