name: Deploy

on: [workflow_call]

env:
  OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: cargohub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}

      - name: Debug Variables
        run: |
          echo "OWNER=${OWNER}"
          echo "OWNER_LC=${OWNER,,}"
          echo "IMAGE_NAME=${IMAGE_NAME}"

      - name: Build and Push the Docker image (push to main)
        if: github.event_name == 'push'
        run: |
          docker build . --tag ghcr.io/$OWNER_LC/$IMAGE_NAME:latest
          docker push ghcr.io/$OWNER_LC/$IMAGE_NAME:latest

      - name: Send HTTP request with curl (only on push)
        if: github.event_name == 'push'
        run: |
          curl -X POST -k "https://52.90.108.213:9443/api/stacks/webhooks/c033a3b4-1224-4e87-8589-794ca0b71d30"
