name: Test

on: [workflow_call]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Run code formatting check (continue on error)
        run: dotnet format --verify-no-changes
        continue-on-error: true

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore

      - name: Run code analysis
        run: dotnet build --configuration Release /warnaserror
